apiVersion: batch/v1
kind: Job
metadata:
  name: fraud-preprocess
  labels:
    {{- include "fraud-preprocess.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: preprocess
        {{- include "fraud-preprocess.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      affinity:
        nodeAffinity:
          {{- toYaml .Values.nodeAffinity | nindent 10 }}
      tolerations:
        {{- toYaml .Values.gpu.tolerations | nindent 8 }}
      containers:
        - name: preprocess
          image: {{ if .Values.image.fullImage }}{{ .Values.image.fullImage | quote }}{{ else }}{{ printf "%s/%s/%s:%s" .Values.image.registry (include "fraud-preprocess.imageNamespace" .) .Values.image.repository .Values.image.tag | quote }}{{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fraud-data
