{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  labels:
    {{- include "fraud-init-pipeline.labels" . | nindent 4 }}
type: Opaque
data:
  rootUser: {{ .Values.minio.rootUser | b64enc | quote }}
  rootPassword: {{ .Values.minio.rootPassword | b64enc | quote }}
{{- end }}
