apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-models
  labels:
    {{- include "fraud-init-pipeline.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.models.size }}
  {{- if .Values.storage.models.className }}
  storageClassName: {{ .Values.storage.models.className }}
  {{- end }}
