{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fraud-triton
  labels:
    app.kubernetes.io/component: triton
    {{- include "fraud-inference.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: fraud-triton
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
