apiVersion: v1
kind: Service
metadata:
  name: fraud-triton
  labels:
    app.kubernetes.io/component: triton
    {{- include "fraud-inference.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: fraud-triton
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: grpc
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 8002
      targetPort: 8002
